### ISSUE TITLE
"Vessel" gauge does not update when vessel renamed...

### ISSUE THREAD

**Issue by cerebrate** [Nereid42/NanoGauges#6]
...from command pod right-click menu.

Tested with KSP 1.2.2 and latest NanoGauges release.

**Comment by Nereid42** [comment]
Thanks. I will try to correct this for the 1.3 update. But I need a few days...
 

Gesendet: Freitag, 26. Mai 2017 um 18:40 Uhr
Von: "Alistair Young" <notifications@github.com>
An: Nereid42/NanoGauges <NanoGauges@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Nereid42/NanoGauges] "Vessel" gauge does not update when vessel renamed... (#6)


...from command pod right-click menu.

Tested with KSP 1.2.2 and latest NanoGauges release.

**Comment by Nereid42** [comment]
Issue fixed long ago...
